version = 5.6.0
archive_dir = /etc/letsencrypt/archive/turn.conjuntos.app
cert = /etc/letsencrypt/live/turn.conjuntos.app/cert.pem
privkey = /etc/letsencrypt/live/turn.conjuntos.app/privkey.pem
chain = /etc/letsencrypt/live/turn.conjuntos.app/chain.pem
fullchain = /etc/letsencrypt/live/turn.conjuntos.app/fullchain.pem
[renewalparams]
account = ae0c44e5a699c20f0950269924cefdb6
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-06-20T08:50:07
