use axum::response::Html;
use axum::Json;
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "ConjuntOS® 🏘️ API",
        description = "Rust backend for the ConjuntOS® 🏘️ residential-complex platform. \
                       Contract per specs/constitution.md Law 5.",
        version = "0.1.0"
    ),
    paths(
        crate::routes::healthz,
        crate::domains::auth_routes::login,
        crate::domains::auth_routes::me,
        crate::domains::auth_routes::logout,
        crate::domains::auth_routes::change_password,
        crate::domains::auth_routes::switch_role,
        crate::domains::auth_routes::ws_ticket,
        crate::domains::usuarios::handlers::get_profile,
        crate::domains::usuarios::handlers::update_profile,
        crate::domains::usuarios::handlers::delete_account,
        crate::domains::conjuntos::handlers::list_conjuntos,
        crate::domains::conjuntos::handlers::create_conjunto,
        crate::domains::conjuntos::handlers::update_conjunto,
        crate::domains::notificaciones::handlers::list_notificaciones,
        crate::domains::notificaciones::handlers::mark_leidas,
        crate::domains::notificaciones::handlers::subscribe_push,
        crate::domains::notificaciones::handlers::unsubscribe_push,
        crate::domains::vigilancia::handlers::listar_visitas_hoy,
        crate::domains::vigilancia::handlers::crear_visita_vigilancia,
        crate::domains::vigilancia::handlers::crear_visita_residente,
        crate::domains::vigilancia::handlers::aprobar_visita,
        crate::domains::vigilancia::handlers::listar_paquetes,
        crate::domains::vigilancia::handlers::crear_paquete,
        crate::domains::vigilancia::handlers::entregar_paquete,
        crate::domains::vigilancia::handlers::vigilancia_stats,
        crate::domains::vigilancia::handlers::paquetes_mios,
        crate::domains::vigilancia::handlers::comunicaciones,
        crate::domains::parqueadero::handlers::parqueadero_mio,
        crate::domains::parqueadero::handlers::crear_vehiculo,
        crate::domains::parqueadero::handlers::mapa,
        crate::domains::parqueadero::handlers::crear_celdas,
        crate::domains::parqueadero::handlers::actualizar_celda,
        crate::domains::parqueadero::handlers::asignar_celda,
        crate::domains::parqueadero::handlers::liberar_celda,
        crate::domains::parqueadero::handlers::registros,
        crate::domains::parqueadero::handlers::ronda_de_hoy,
        crate::domains::parqueadero::handlers::crear_ronda,
        crate::domains::parqueadero::handlers::puntos_ronda_handler,
        crate::domains::parqueadero::handlers::crear_punto_ronda,
        crate::domains::parqueadero::handlers::registrar_checkpoint,
        crate::domains::parqueadero::handlers::checkpoints_de_ronda,
        crate::domains::parqueadero::handlers::parqueadero_stats,
        crate::domains::parqueadero::handlers::listar_solicitudes,
        crate::domains::parqueadero::handlers::mis_solicitudes_inquilino,
        crate::domains::parqueadero::handlers::inquilino_aprobar,
        crate::domains::parqueadero::handlers::inquilino_rechazar,
        crate::domains::parqueadero::handlers::mis_sesiones,
        crate::domains::parqueadero::handlers::sesion_de_celda,
        crate::domains::parqueadero::handlers::cerrar_sesion,
        crate::domains::parqueadero::handlers::mis_cargos_pendientes,
        crate::domains::parqueadero::handlers::cargo_aprobar,
        crate::domains::parqueadero::handlers::cargo_rechazar,
        crate::domains::parqueadero::handlers::reservas_disponibilidad,
        crate::domains::parqueadero::handlers::crear_reserva,
        crate::domains::parqueadero::handlers::mis_reservas,
        crate::domains::parqueadero::handlers::reservas_proximas,
        crate::domains::parqueadero::handlers::cancelar_reserva,
        crate::domains::parqueadero::handlers::reserva_marcar_llegada,
        crate::domains::parqueadero::handlers::aprobar_solicitud,
        crate::domains::parqueadero::handlers::rechazar_solicitud,
        crate::domains::parqueadero::handlers::editar_solicitud,
        crate::domains::parqueadero::handlers::borrar_solicitud,
        crate::domains::reservas::handlers::listar_areas,
        crate::domains::reservas::handlers::slots,
        crate::domains::reservas::handlers::listar_reservas,
        crate::domains::reservas::handlers::crear_reserva,
        crate::domains::pagos::handlers::listar_pagos,
        crate::domains::pagos::handlers::pagar,
        crate::domains::comunicaciones::handlers::listar_anuncios,
        crate::domains::comunicaciones::handlers::crear_anuncio,
        crate::domains::comunicaciones::handlers::actualizar_anuncio,
        crate::domains::comunicaciones::handlers::eliminar_anuncio,
        crate::domains::comunicaciones::handlers::directorio,
        crate::domains::uploads::handlers::subir_imagen,
        crate::domains::uploads::handlers::subir_archivo,
        crate::domains::solicitudes::handlers::listar_solicitudes,
        crate::domains::solicitudes::handlers::crear_solicitud,
        crate::domains::tramites::handlers::listar_tramites,
        crate::domains::tramites::handlers::crear_tramite,
        crate::domains::tramites::handlers::resolver_tramite,
        crate::domains::clasificados::handlers::listar_clasificados,
        crate::domains::clasificados::handlers::crear_clasificado,
        crate::domains::inmuebles::handlers::listar_inmuebles,
        crate::domains::inmuebles::handlers::crear_inmueble,
        crate::domains::admin_stats::admin_stats,
        crate::domains::analytics::handlers::demografia,
        crate::domains::pases_temporales::handlers::crear_pase,
        crate::domains::pases_temporales::handlers::mis_pases,
        crate::domains::pases_temporales::handlers::mi_pase,
        crate::domains::pases_temporales::handlers::validar_pase,
        crate::domains::pases_temporales::handlers::revocar_pase,
        crate::domains::pases_temporales::handlers::editar_pase,
        crate::domains::usuarios::handlers::directorio,
        crate::domains::admin_usuarios::listar_usuarios,
        crate::domains::admin_usuarios::detalle_usuario,
        crate::domains::admin_usuarios::editar_usuario,
        crate::domains::admin_usuarios::invitar_residente,
        crate::domains::admin_areas::listar_areas,
        crate::domains::admin_areas::crear_area,
        crate::domains::admin_areas::editar_area,
        crate::domains::admin_areas::eliminar_area,
        crate::domains::admin_areas::listar_reservas,
        crate::domains::admin_finanzas::resumen,
        crate::domains::admin_finanzas::listar_pagos,
        crate::domains::admin_finanzas::listar_gastos,
        crate::domains::admin_finanzas::crear_gasto,
        crate::domains::admin_finanzas::editar_gasto,
        crate::domains::admin_finanzas::eliminar_gasto,
        crate::domains::admin_finanzas::morosidad,
        crate::domains::ad_spaces::handlers::active_for_feed,
        crate::domains::ad_spaces::handlers::list,
        crate::domains::ad_spaces::handlers::get_one,
        crate::domains::ad_spaces::handlers::create,
        crate::domains::ad_spaces::handlers::update,
        crate::domains::ad_spaces::handlers::delete_handler,
        crate::domains::ad_spaces::handlers::click,
        crate::domains::ad_spaces::handlers::impression,
        crate::domains::chat::handlers::list_messages,
        crate::domains::chat::handlers::send_message,
        crate::domains::chat::handlers::list_conversations,
        crate::domains::chat::handlers::get_thread,
        crate::domains::chat::handlers::admin_send,
        crate::domains::citofonia::handlers::citofonia_token,
        crate::domains::citofonia::handlers::call,
        crate::domains::solicitudes::handlers::mis_asignadas,
        crate::domains::solicitudes::handlers::ver_solicitud,
        crate::domains::solicitudes::handlers::comentarios,
        crate::domains::solicitudes::handlers::agregar_comentario,
        crate::domains::solicitudes::handlers::cambiar_estado,
        crate::domains::inmuebles::handlers::actualizar_inmueble,
        crate::domains::sos::crear,
        crate::domains::sos::listar,
        crate::domains::sos::mi_activa,
        crate::domains::sos::atender,
        crate::domains::sos::resolver,
        crate::domains::sos::cancelar,
        crate::domains::encuestas::listar,
        crate::domains::encuestas::crear,
        crate::domains::encuestas::votar,
        crate::domains::encuestas::cerrar,
        crate::domains::multas::listar,
        crate::domains::multas::emitir,
        crate::domains::multas::apelar,
        crate::domains::multas::anular,
        crate::domains::admin_stats::get_status,
        crate::domains::admin_stats::update_status_handler,
        crate::domains::ai::handlers::copilot,
        crate::domains::ai::handlers::translate,
        crate::domains::ai::handlers::consensuar,
        crate::domains::ai::handlers::get_acta,
        crate::domains::ai::handlers::generate_acta,
        crate::domains::ai::handlers::acta_pdf,
        crate::domains::ai::handlers::asistente,
        crate::domains::asamblea::handlers::create_asamblea,
        crate::domains::asamblea::handlers::get_pairing,
        crate::domains::asamblea::handlers::create_pairing,
        crate::domains::asamblea::handlers::update_votacion,
        crate::domains::asamblea::handlers::list_votos,
        crate::domains::asamblea::handlers::cast_voto,
        crate::domains::asamblea::handlers::update_turno,
        crate::domains::asamblea::handlers::update_poder,
        crate::domains::asamblea::handlers::livekit_token,
        crate::domains::comite_convivencia::handlers::comite_actual,
        crate::domains::comite_convivencia::handlers::crear_comite,
        crate::domains::comite_convivencia::handlers::historico_comites,
        crate::domains::comite_convivencia::handlers::agregar_miembro,
        crate::domains::comite_convivencia::handlers::desactivar_miembro,
        crate::domains::comite_convivencia::handlers::listar_casos,
        crate::domains::comite_convivencia::handlers::crear_caso,
        crate::domains::comite_convivencia::handlers::stats,
        crate::domains::comite_convivencia::handlers::actualizar_caso,
        crate::domains::comite_convivencia::handlers::asignar_miembro,
        crate::domains::comite_convivencia::handlers::registrar_mediacion,
        crate::domains::comite_convivencia::handlers::generar_acta,
        crate::domains::comite_convivencia::handlers::firmar_acta,
        crate::domains::comite_convivencia::handlers::listar_unidades,
        crate::domains::documentos::actualizar_documentos,
        crate::domains::documentos::listar_vacunas,
        crate::domains::documentos::crear_vacuna,
        crate::domains::documentos::eliminar_vacuna,
        crate::domains::pagos::handlers::estado_pago,
        crate::domains::reservas::handlers::listar_reservas_area_hoy,
        crate::domains::reservas::handlers::verificar_reserva,
        crate::domains::servicios::listar_admin,
        crate::domains::servicios::stats_admin,
        crate::domains::servicios::actualizar,
        crate::domains::servicios::listar_comentarios,
        crate::domains::servicios::agregar_comentario,
        crate::domains::servicios::listar_transiciones,
        crate::domains::vigilancia::handlers::entregar_correspondencia_handler,
        crate::domains::vigilancia::handlers::resolver_novedad_handler,
        crate::domains::vigilancia::preregistro::preregistrar,
        crate::domains::vigilancia::preregistro::escanear,
    ),
    tags(
        (name = "ops", description = "Health and operational endpoints"),
        (name = "auth", description = "Session management (JWT via ec_session cookie or Bearer)"),
        (name = "usuarios", description = "Profile and account"),
        (name = "superadmin", description = "Cross-tenant administration"),
        (name = "notificaciones", description = "In-app notifications, web-push subscriptions, and native (Expo/FCM/APNs) push tokens"),
        (name = "vigilancia", description = "Gate operations: visits, packages, stats"),
        (name = "parqueadero", description = "Parking: vehicles, cell map, audit log, rounds"),
        (name = "reservas", description = "Common areas and amenity reservations"),
        (name = "pagos", description = "Administration fees and utility bills"),
        (name = "comunicaciones", description = "Announcements board and resident directory"),
        (name = "solicitudes", description = "PQRS service requests"),
        (name = "tramites", description = "Administrative trámites (pets, vehicles, moves) with approval flow"),
        (name = "clasificados", description = "Resident classifieds marketplace"),
        (name = "inmuebles", description = "Real-estate listings inside the conjunto"),
        (name = "admin", description = "Tenant administration dashboards"),
        (name = "sos", description = "Panic / SOS emergency alerts"),
        (name = "encuestas", description = "Resident polls and voting"),
        (name = "multas", description = "Fines and appeals"),
        (name = "convivencia", description = "Coexistence committee: cases, mediation, minutes"),
        (name = "asambleas", description = "Assemblies: pairing, minutes, live copilot, voting"),
        (name = "citofonia", description = "Intercom (LiveKit) calls and tokens"),
        (name = "chat", description = "Resident ↔ admin messaging"),
        (name = "ai", description = "AI assistant (Ley 675 + copilot)"),
        (name = "ad-spaces", description = "Sponsored ad spaces")
    )
)]
pub struct ApiDoc;

pub async fn openapi_json() -> Json<utoipa::openapi::OpenApi> {
    Json(ApiDoc::openapi())
}

/// Swagger UI loaded from CDN so the build needs no bundled assets.
pub async fn docs_html() -> Html<&'static str> {
    Html(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>ConjuntOS® 🏘️ API docs</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css" />
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    window.onload = () => {
      SwaggerUIBundle({ url: '/api/v1/openapi.json', dom_id: '#swagger-ui' });
    };
  </script>
</body>
</html>"#,
    )
}
